name: Demonstration of baas-webui

on:
  push:
    branches: [ "demo" ]
  pull_request:
    branches: [ "demo" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'pnpm'
    
    # Install pnpm globally
    - run: npm install -g pnpm
    
    # Install dependencies using pnpm
    - run: pnpm install
    
    # Build the project
    - run: pnpm run build
